<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SportsBooking.Contracts\SportsBooking.Contracts.csproj" />
      <ProjectReference Include="..\SportsBooking.Domain\SportsBooking.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Reviews\" />
      <Folder Include="Users\" />
    </ItemGroup>

</Project>
